openapi: 3.0.1

info:
  title: Week Mates
  version: 1.0.0

servers:
  - url: http://api-server.localhost/

tags:
  - name: users
    description: Operations about users

paths:
  /users/signup:
    post:
      tags:
        - users
      summary: Create new user
      requestBody:
        required: true
        description: User identity information
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
            examples:
              valid:
                value:
                  email: test@example.com
                  password: 12345678
              empty:
                value:
                  email: ""
                  password: ""

      responses:
        200:
          description: Request syntax OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  error_code:
                    type: string
                  data:
                    type: object
                    properties:
                      validation_errors:
                        type: array
                        items:
                          type: object
                          properties:
                            field:
                              type: string
                            message:
                              type: string
              examples:
                valid:
                  value:
                    success: true
                    error_code: 0
                    data: {}
                empty:
                  value:
                    success: false
                    error_code: 0 # Fix
                    data:
                      - field: email
                        message: Please input email.
                      - field: password
                        message: Please input password.
        400:
          description: Request syntax error

  /users/signin:
    post:
      tags:
        - users
      summary: Identify user and return access key
      requestBody:
        required: true
        description: User identity information
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
            examples:
              valid:
                value:
                  email: test@example.com
                  password: 12345678
              empty:
                value:
                  email: ""
                  password: ""
              identify_failed:
                value:
                  email: test@example.com
                  password: abcdefgh
      responses:
        200:
          description: Request syntax OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  error_code:
                    type: string
                  data:
                    type: object
                    properties:
                      validation_errors:
                        type: array
                        items:
                          type: object
                          properties:
                            field:
                              type: string
                            message:
                              type: string
              examples:
                valid:
                  value:
                    success: true
                    error_code: 0
                    data: {}
                empty:
                  value:
                    success: false
                    error_code: 0 # Fix
                    data:
                      - field: email
                        message: Please input email.
                      - field: password
                        message: Please input password.
                identify_failed:
                  value:
                    success: false
                    error_code: 0 # Fix
                    data:
                      - field: identify
                        message: Please check email and password. No user has been matched with the identification data.
        400:
          description: Request syntax error

components: {}

